### ISSUE TITLE
Eliminate yeoman installation

### ISSUE THREAD

**Issue by njordhov** [blockstack/blockstack-app-generator#57]
The steps can be simplified by not requiring installation of yeoman but instead specify it in npm project creation: 

````shell
npm init yo blockstack
````

Assuming npm >=v6.1.0 which introduced use of a custom package with npm init to scaffold a project.

**Comment by zone117x** [comment]
Users are already attempting to use non-global installs and running into problems:

https://blockstack.slack.com/archives/C07TM0PSM/p1566863831168900 --
> Hey all, does anyone get the following error message when they try to run npm create yo blockstack on Windows Powershell? I first updated my npm version and am now using npm version 6.11.2. Even after downloading the latest version, I still get the following error.
>
```
npm create yo blockstack
npx: installed 15 in 11.618s
Command failed: C:\"Program Files"\nodejs\node.exe "C:\Users\jenni\AppData\Roaming\npm\npm" config get cache --parseable
C:\Users\jenni\AppData\Roaming\npm\npm:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

---

The problem is with the `create-yo` dependency, see https://github.com/boneskull/create-yo/issues/4#issuecomment-523661040

One way we can fix this on our end is to integrate yeoman (see https://yeoman.io/authoring/integrating-yeoman.html) so that something like `npm init blockstack` can work.
